// Theme tokens (extracted from HRMS screenshot)
export const T = {
  sidebar: "#2b2d31",
  sidebarText: "#c9cdd4",
  sidebarActive: "#3d5a99",
  sidebarHover: "#35373c",
  topbar: "#ffffff",
  bg: "#f0ede8",
  card: "#ffffff",
  navy: "#3d5a99",
  navyDark: "#2d4373",
  navyLight: "#eef1f8",
  red: "#e03131",
  text: "#1a1b1e",
  textMuted: "#6b7280",
  textLight: "#9ca3af",
  border: "#e5e7eb",
  green: "#2f9e44",
  amber: "#e67700",
  danger: "#c92a2a",
  success: "#2f9e44",
};

// Tiny style helpers
export const s = {
  flex: (align = "center", justify = "flex-start", gap = 0) => ({
    display: "flex",
    alignItems: align,
    justifyContent: justify,
    gap,
  }),
  card: (accent = T.navy) => ({
    background: T.card,
    borderRadius: 10,
    borderLeft: `4px solid ${accent}`,
    boxShadow: "0 1px 4px rgba(0,0,0,.07)",
    padding: "20px 24px",
    position: "relative",
  }),
  badge: (bg, color) => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    fontWeight: 600,
    padding: "3px 10px",
    borderRadius: 20,
    background: bg,
    color,
    whiteSpace: "nowrap",
    letterSpacing: 0.3,
  }),
  btn: (variant = "outline") => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: variant === "primary" ? "9px 20px" : "8px 18px",
    borderRadius: 7,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    border: variant === "primary" ? "none" : `1.5px solid ${T.border}`,
    background: variant === "primary" ? T.navy : T.card,
    color: variant === "primary" ? "#fff" : T.text,
    transition: "all .15s",
  }),
  input: {
    width: "100%",
    padding: "9px 12px",
    borderRadius: 7,
    border: `1.5px solid ${T.border}`,
    fontSize: 13,
    background: T.card,
    color: T.text,
    fontFamily: "inherit",
    outline: "none",
  },
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: T.textMuted,
    marginBottom: 5,
    display: "block",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
};
